### ISSUE TITLE
Issues with PostActivity/LikedPostActivity functionality

### ISSUE THREAD

**Issue by aptgarcia** [khou4644/RecipeSaveShareVSP24#1]
Added new branch PostActivity with alot of changes such as adding RecyclerView, LiveData, creating new packages, Activities and RecyclerView which has the PostAdapter for PostActivity. Biggest issue is currently getting the menu option to select view Liked Posts to work, the intent is in the code and should work but have not figured out the solution yet. Also the like/dislike button functionality is clickable but completely broken, I need more work to get the like/dislike buttons to work properly with the RecyclerView for PostActivity. 

Also thinking of implementing a back button functionality within the Activities where it is necessary. If user misclicks an input and is taken to wrong page we can just go back to previous page. Will fix soon in upcoming week before project is due. Would say about 60-70% done with all these new changes.

please do not pull request into main and work on this branch/pull this branch separately until bugs are fixed, once fixed we can close this issue and merge into main using GitHub pull request.

**Comment by aptgarcia** [comment]
Like/dislike buttons work correctly now with recyclerView for PostActivity. Has been pushed and commited as PostActivity branch and merged onto master.
Still working on PostActivity leading to LikedPostActivity,
Back button functionality is being worked on by rocket.

**Comment by khou4644** [comment]
Back button in example_menu was made functional, but was scrapped in favor of the "left-arrow" back button for simplicity and convenience. "left-arrow" back button functionality is implemented and working as intended.

**Comment by khou4644** [comment]
Issue resolved. "Liked Posts" now only appears in the example_menu when in PostActivity from "All User Posts" button in landing page, correctly displaying the posts that the user has liked.
